---
ID: "7c8bbba2-3c48-40f2-86f2-8facc804296d"
Parent: "06a3d468-3ce7-4982-b6cd-194832fb60ba"
Template: "06a3d468-3ce7-4982-b6cd-194832fb60ba"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Teaser/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{5AA8304F-8F94-454D-9857-E88F8882FDE7}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "fd14e502-9416-4445-b6a0-b56ad71e03c2"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251127T072603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shivprasad.kharade@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shivprasad.kharade@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7eaecc2-3c57-447f-8d10-bf99209a1b8a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivprasad.kharade@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251127T072625Z
